### ISSUE TITLE
More troubleshooting help?

### ISSUE THREAD

**Issue by benhamill** [rking/vim-detailed#13]
After installing this, my vim looks like the "this is misbehaving" screenshot.

```
$ echo $TERM
xterm-256color
```

I also tried `screen-256color`, but since I'm just using xterm, I was unsurprised when it made no change. I've been using solarized before now, and I had tweaked my terminal's color settings to match, but I commented all that out and reloaded the file, so, I don't expect that's the issue.

I'm using xterm on Arch Linux and vim (not gvim or vi or another variant). Is there something else I should try? I'm going to monkey with it a bit more and if I figure anything out, I'll try to remember to post here (and, if appropriate, make a PR to add to the README), but any further guidance would be appreciated. :smile:

**Comment by rking** [comment]
Is tmux in the mix?

**Comment by benhamill** [comment]
Nope. Just vanilla xterm. Note: If most users are using iTerm whatever, there may be some unexplored GNU difference. I'm willing to be a guinea pig and help sort it out, but I'm not super familiar with the territory, so I'm not sure what to try.

**Comment by rking** [comment]
Actually, I use Linux, but only urxvt.

Does switching to urxvt or gnome-terminal help?

Big thanks for this.

(By the way, is it just me or does Github eat newlines and all Markdownish formatting when you reply via email?)

**Comment by rking** [comment]
I was able to get it to work in xterm. It definitely required `TERM=xterm-256color`, but other than that, no tricks.

**Comment by benhamill** [comment]
I haven't had the time to mess with this more. I've got a ton of stuff in my .xinitrc and .vimrc and whatever. I'm going to make a new user on this computer and install just detailed and see how it goes. Might be some conflict in my current environment. I'll post here with an update after.

**Comment by rking** [comment]
I just tried it out using your `dotfiles` repo, and it works fine for me.

The bisection must continue!

**Comment by benhamill** [comment]
News: I just created a new user on my laptop and cloned down my .vimrc and .vim, installed details and it worked great. So it must be something with my X setup. Will update when I have more info.

**Comment by benhamill** [comment]
OK. So it's working, now, on my Lenovo. Something is clearly up on my Air at work. Or else user error on my part. I'll have to see how it goes on that machine, then, later on.

**Comment by rking** [comment]
Well, fwiw, you're not imagining things. I've seen similar, in passing, yet not fully captured.

## Thank you for the feedback!

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by benhamill** [comment]
Aaaaand now it's working fine on my Air. No idea. Cannot replicate. Anyway, thanks for spending time on... whatever the hell this was. Now I'll give it a test run and see how I like it.
