### ISSUE TITLE
Vundle install instructions?

### ISSUE THREAD

**Issue by djcp** [rking/vim-detailed#14]
I was hoping

``` vim
Bundle 'rking/vim-detailed'
```

would work to install this via vundle, but apparently there's more to it than that. Can we get a README update on how installing should work under vundle?

**Comment by rking** [comment]
I don't enable it by default.

You have to add to your vim rc stuff:

```
colorscheme detailed
```

Do you think we should enable by default?

Daniel Collis-Puro notifications@github.com wrote:

> I was hoping
> 
> ``` vim
> Bundle 'rking/vim-detailed'
> ```
> 
> would work to install this via vundle, but apparently there's more to
> it than that. Can we get a README update on how installing should work
> under vundle?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rking/vim-detailed/issues/14

## 

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

**Comment by calebhearth** [comment]
@djcp:

``` vim
" ~/.vimrc.bundles
Bundle 'rking/vim-detailed'

" ~/.vimrc
colorscheme detailed
```
