### ISSUE TITLE
macvim/vim tips

### ISSUE THREAD

**Issue by gguimaraesbr** [rking/vim-detailed#16]
Don't ask me why but I was only able to make it work by setting t_Co=8 in the .vimrc and redifining the theme in the .gvimrc (colorscheme detailed).

My terminal is set to declare itself as 'xterm-256color'

**Comment by rking** [comment]
Please commit any doc (or code) tweaks you have straight into master.

I also had trouble on OS X, and hacked around it with `TERM=screen` — but I haven't figured out why these hacks are necessary.

**Comment by gguimaraesbr** [comment]
Closing since I'm not using vim anymore.
