### ISSUE TITLE
Surprise conditionals should be highlighted as conditional

### ISSUE THREAD

**Issue by calebhearth** [rking/vim-detailed#19]
![2013-07-16 at 11 33 57 am](https://f.cloud.github.com/assets/711717/805767/26c0be32-ee2d-11e2-903a-dd1ca7727487.png)

Lines with trailing conditionals should be highlighted as yellow rather than green, so that it's clearer that they have surprises at the end.

**Comment by rking** [comment]
I agree.

This will be a matter of overriding the `syntax/ruby.vim` that governs this, and I didn't get in there to mess with it.

You're totally right, though.
