### ISSUE TITLE
Is vim-detailed project dead?

### ISSUE THREAD

**Issue by wwalker** [rking/vim-detailed#24]
There have been no merges or commits since June 2013.

RKing's domain (sharpsaw.org) is dead.

This is a quite cool colorscheme (maybe the only high color vim colorscheme?).

I'd like to see it continue.

RKing, are you out there?

**Comment by wikimatze** [comment]
Have you tried emailing him?

**Comment by wwalker** [comment]
Yes, his listed email domain is dead and gone.

**Comment by wikimatze** [comment]
I will close this issue then.
